### ISSUE TITLE
非题目创建者的题目管理无法看到自己的提交记录

### ISSUE THREAD

**Issue by AppOfficer** [oimasterkafuu/betaoj#41]
**描述错误**
非题目创建者的题目管理无法看到自己的提交记录。

**重现步骤**
重现错误的步骤：
1. 前往题目管理所管理的题目；
2. 输入代码并提交；
3. 在提交记录详情界面看到错误“您没有权限进行此操作”。虽然提交记录详情无法查看，但是可以在题目的提交记录列表中看到。

**预期行为**
题目管理应能看到自己的提交记录的详细信息。

**桌面端（请提供以下信息）：**
 - 操作系统：所有系统
 - 浏览器：所有浏览器
 - 版本：所有版本

**Comment by oimasterkafuu** [comment]
Done
